"""Compatibility boundary: candidate-specific private evidence is not distributed."""

CANDIDATE_ID = '__private_c6_exact_final_boundary_adapter_unavailable__'
RECORDING_DATE = '__private_c6_exact_final_boundary_adapter_unavailable__'
REVIEWED_SRT_SHA256 = '__private_c6_exact_final_boundary_adapter_unavailable__'
PIPELINE_SRT_SHA256 = '__private_c6_exact_final_boundary_adapter_unavailable__'
DECISION_LEDGER_SHA256 = '__private_c6_exact_final_boundary_adapter_unavailable__'
TRUTH_DIFF_SHA256 = '__private_c6_exact_final_boundary_adapter_unavailable__'
RECORD_SHA256 = '__private_c6_exact_final_boundary_adapter_unavailable__'
FINAL_SPEAKER_SRT_SHA256 = '__private_c6_exact_final_boundary_adapter_unavailable__'
SPEAKER_ASS_SHA256 = '__private_c6_exact_final_boundary_adapter_unavailable__'
REPLAY_PLAN_EXPECTED_VIDEO_SHA256 = '__private_c6_exact_final_boundary_adapter_unavailable__'
FROZEN_DELIVERY_VIDEO_SHA256 = '__private_c6_exact_final_boundary_adapter_unavailable__'
CHAT_SHA256 = '__private_c6_exact_final_boundary_adapter_unavailable__'
BOUNDARY_AUDIT_SHA256 = '__private_c6_exact_final_boundary_adapter_unavailable__'
AUTHORITY_SELF_HASH = '__private_c6_exact_final_boundary_adapter_unavailable__'
STAGE_JSON_SHA256 = '__private_c6_exact_final_boundary_adapter_unavailable__'
SOURCE_MEDIA_IDENTITY = '__private_c6_exact_final_boundary_adapter_unavailable__'
SOURCE_LOCAL_START_MS = '__private_c6_exact_final_boundary_adapter_unavailable__'
SOURCE_LOCAL_END_MS = '__private_c6_exact_final_boundary_adapter_unavailable__'
DELIVERY_LOCAL_START_MS = '__private_c6_exact_final_boundary_adapter_unavailable__'
DELIVERY_LOCAL_END_MS = '__private_c6_exact_final_boundary_adapter_unavailable__'
ABSOLUTE_SOURCE_START_MS = '__private_c6_exact_final_boundary_adapter_unavailable__'
ABSOLUTE_SOURCE_END_MS = '__private_c6_exact_final_boundary_adapter_unavailable__'
EXPECTED_CUE_COUNT = '__private_c6_exact_final_boundary_adapter_unavailable__'
OLD_CUE17 = '__private_c6_exact_final_boundary_adapter_unavailable__'
NEW_CUE17 = '__private_c6_exact_final_boundary_adapter_unavailable__'

class C6ExactFinalBoundaryAdapterError(ValueError):
    reason_code = "PRIVATE_CANDIDATE_AUTHORITY_UNAVAILABLE"

def build_c6_exact_final_reviewer(*args, **kwargs):
    return None
