"""Field-level locator and immutability contract for package relocation.

一个在别的主机（wsl / Mac）上产完的切片包，其 JSON 文档里记的是**产它那台机
的绝对路径**。搬进 free 的交付链时只允许投影「运行期定位符」这一类字段，证据与
出处必须逐字节保持产出主机写下的值。本模块就是那条界线的机械定义：

- ``*_PATH_POINTERS``：允许被改写的定位符（白名单，按文档种类分）；
- ``_*_ROOT_ROLES``：每个定位符**必须**落在哪个根角色下（package / candidate /
  repo）。同哈希的文件在不同物理角色下仍然不可互换——例如
  ``speaker.profile`` 只能来自 repo，``speaker.speaker_override`` 只能来自
  candidate 或 repo；
- ``_*_FROZEN_PREFIXES``：冻结证据子树。这些子树里出现产出主机路径是合法的
  （它们记录的是"当时在哪台机上算的"），但**不得被改写**；
- :func:`reject_unknown_wsl_paths`：安全网。既不在定位符白名单、也不在冻结证据
  子树里的地方出现产出主机路径 → 拒绝，而不是"尽力搬"。

来源：2026-08-09 87finish 交付链在 free 上的一次性工具
``/tmp/package_relocation_contract_fasttrack_0809.py``（BV1hfuS6EENb /
BV1houS6SEF3 两条已发布件都经它落地）。当时没有上游化，于是 wsl 产的每条片都要
手工伺候；这里把它收编进仓库，供 ``scripts/import_external_package.py`` 复用。
"""

from __future__ import annotations

import copy
import re
from collections.abc import Iterator, Mapping, Sequence
from typing import Any


class PackageRelocationError(RuntimeError):
    """The package could not be relocated without weakening its bindings."""


JsonPointer = tuple[str, ...]
ROOT_ROLES = ("package", "candidate", "repo")

RECORD_PATH_POINTERS: frozenset[JsonPointer] = frozenset(
    {
        ("media_path",),
        ("subtitle_path",),
        ("human_text_correction_manifest_path",),
        ("chat_authority_audit_path",),
        ("clip_context_path",),
        ("redelivery_baseline_audit_path",),
        ("subtitle_regression_audit_path",),
        ("talk_filler_audit_path",),
        ("text_finalization_manifest_path",),
        ("speaker_review_srt_path",),
        ("subtitle_ass_path",),
        ("speaker_finalization_manifest_path",),
        ("burned_preview", "path"),
        ("burned_preview", "ass_path"),
        ("publish_staging", "cover_path"),
        ("publish_staging", "publish_json_path"),
        ("publish_staging", "cover_generation", "final_cover"),
        ("publish_staging", "cover_generation", "pre_overlay_path"),
        ("publish_staging", "cover_generation", "ai_background"),
        ("publish_staging", "cover_generation", "reference_image"),
        (
            "publish_staging",
            "cover_generation",
            "rendered_text_pixels",
            "mask_path",
        ),
        (
            "publish_staging",
            "cover_generation",
            "rendered_text_pixels",
            "pre_overlay_path",
        ),
    }
)
PUBLISH_PATH_POINTERS: frozenset[JsonPointer] = frozenset(
    {
        ("video_path",),
        ("cover_path",),
        ("cover_generation", "final_cover"),
        ("cover_generation", "pre_overlay_path"),
        ("cover_generation", "ai_background"),
        ("cover_generation", "reference_image"),
        ("cover_generation", "rendered_text_pixels", "mask_path"),
        ("cover_generation", "rendered_text_pixels", "pre_overlay_path"),
    }
)
# Chat authority is normally immutable audit evidence.  Only these final
# artifact locators are regenerated by producer finalization, so they share
# the record/publish relocation boundary instead of permitting an ad-hoc
# recursive rewrite in a recovery finalizer.
CHAT_PATH_POINTERS: frozenset[JsonPointer] = frozenset(
    {
        ("final_text_srt_path",),
        ("final_speaker_srt_path",),
        ("speaker_ass_path",),
        ("burn_binding", "burned_media_path"),
        ("burn_binding", "ass_path"),
    }
)
SPEAKER_PATH_KEYS = frozenset(
    {
        "source_media",
        "text_final_srt",
        "profile",
        "speaker_override",
        "source_session_anchor_manifest",
        "mixed_overlap_evidence",
        "output_review_srt",
        "output_ass",
    }
)
SPEAKER_PATH_POINTERS: frozenset[JsonPointer] = frozenset({(key,) for key in SPEAKER_PATH_KEYS})

# Same-hash artifacts are still not interchangeable across physical roles.
_RECORD_ROOT_ROLES: Mapping[JsonPointer, frozenset[str]] = {
    **{pointer: frozenset({"package"}) for pointer in RECORD_PATH_POINTERS},
    ("chat_authority_audit_path",): frozenset({"package", "candidate"}),
    ("clip_context_path",): frozenset({"package", "candidate"}),
    ("talk_filler_audit_path",): frozenset({"candidate"}),
}
_PUBLISH_ROOT_ROLES: Mapping[JsonPointer, frozenset[str]] = {
    pointer: frozenset({"package"}) for pointer in PUBLISH_PATH_POINTERS
}
_CHAT_ROOT_ROLES: Mapping[JsonPointer, frozenset[str]] = {
    pointer: frozenset({"package"}) for pointer in CHAT_PATH_POINTERS
}
_SPEAKER_ROOT_ROLES: Mapping[JsonPointer, frozenset[str]] = {
    ("source_media",): frozenset({"package"}),
    ("text_final_srt",): frozenset({"package"}),
    ("profile",): frozenset({"repo"}),
    ("speaker_override",): frozenset({"candidate", "repo"}),
    ("source_session_anchor_manifest",): frozenset({"candidate", "repo"}),
    ("mixed_overlap_evidence",): frozenset({"candidate", "repo"}),
    ("output_review_srt",): frozenset({"package"}),
    ("output_ass",): frozenset({"package"}),
}

_RECORD_FROZEN_PREFIXES: tuple[JsonPointer, ...] = (
    ("burned_preview", "command"),
    ("burned_preview", "branding_intro"),
    ("redelivery_baseline",),
    ("subtitle_regression",),
    ("boundary_audit",),
    ("story_contract",),
    ("selection_scorecard",),
    ("subtitle_timing_qa",),
    ("upload_tags",),
    ("publish_staging", "cover_generation"),
    ("publish_staging", "source_fact_review"),
    ("publish_staging", "title_story_audit"),
    ("publish_staging", "manual_title_repair_authority_consumption"),
    ("publish_staging", "manual_title_keep_authority_consumption"),
    ("publish_staging", "public_text_surface_authority_consumption"),
    ("publish_staging", "recovery_publication_authority"),
)
_PUBLISH_FROZEN_PREFIXES: tuple[JsonPointer, ...] = (
    ("cover_generation",),
    ("source_fact_review",),
    ("title_story_audit",),
    ("manual_title_repair_authority_consumption",),
    ("manual_title_keep_authority_consumption",),
    ("public_text_surface_authority_consumption",),
    ("recovery_publication_authority",),
)
# The chat audit's proposals, owner ledgers, and provenance are frozen.  They
# may retain producing-host locators, but those locators still must resolve to
# one of the three declared relocation roles (enforced by the after-image
# scan), rather than silently accepting an unrelated root.
_CHAT_FROZEN_PREFIXES: tuple[JsonPointer, ...] = ((),)
_SPEAKER_FROZEN_PREFIXES: tuple[JsonPointer, ...] = (
    ("analysis",),
    ("final_decisions",),
    ("ephemeral_runtime_paths",),
    ("runtime_host",),
)


def pointer_text(pointer: JsonPointer) -> str:
    return "/" + "/".join(value.replace("~", "~0").replace("/", "~1") for value in pointer)


def parse_pointer(value: object, *, label: str) -> JsonPointer:
    if not isinstance(value, str) or not value.startswith("/"):
        raise PackageRelocationError(f"{label}: invalid JSON pointer")
    parts = []
    for raw in value[1:].split("/"):
        if re.search(r"~(?![01])", raw):
            raise PackageRelocationError(f"{label}: invalid JSON pointer")
        parts.append(raw.replace("~1", "/").replace("~0", "~"))
    pointer = tuple(parts)
    if pointer_text(pointer) != value:
        raise PackageRelocationError(f"{label}: non-canonical JSON pointer")
    return pointer


def get_value(document: Mapping[str, Any], pointer: JsonPointer) -> object:
    value: object = document
    for key in pointer:
        if not isinstance(value, Mapping) or key not in value:
            return None
        value = value[key]
    return value


def set_value(document: dict[str, Any], pointer: JsonPointer, value: object) -> None:
    parent: object = document
    for key in pointer[:-1]:
        if not isinstance(parent, dict) or key not in parent:
            raise PackageRelocationError(f"missing relocation parent: {pointer_text(pointer)}")
        parent = parent[key]
    if not isinstance(parent, dict) or pointer[-1] not in parent:
        raise PackageRelocationError(f"missing relocation pointer: {pointer_text(pointer)}")
    parent[pointer[-1]] = value


def walk_strings(value: object, pointer: JsonPointer = ()) -> Iterator[tuple[JsonPointer, str]]:
    if isinstance(value, Mapping):
        for key, child in value.items():
            yield from walk_strings(child, (*pointer, str(key)))
    elif isinstance(value, list):
        for index, child in enumerate(value):
            yield from walk_strings(child, (*pointer, str(index)))
    elif isinstance(value, str):
        yield pointer, value


def speaker_record_pointer(pointer: JsonPointer) -> bool:
    return (
        len(pointer) == 2
        and pointer[0] == "speaker_finalization"
        and (pointer[1],) in SPEAKER_PATH_POINTERS
    )


def is_mutable_pointer(kind: str, pointer: JsonPointer) -> bool:
    if kind == "record":
        return pointer in RECORD_PATH_POINTERS or speaker_record_pointer(pointer)
    if kind == "publish":
        return pointer in PUBLISH_PATH_POINTERS
    if kind == "chat":
        return pointer in CHAT_PATH_POINTERS
    return pointer in SPEAKER_PATH_POINTERS


def _under(pointer: JsonPointer, prefix: JsonPointer) -> bool:
    return pointer[: len(prefix)] == prefix


def _is_frozen_pointer(kind: str, pointer: JsonPointer) -> bool:
    if kind == "record" and pointer[:1] == ("speaker_finalization",):
        nested = pointer[1:]
        if nested and not speaker_record_pointer(pointer):
            return any(_under(nested, prefix) for prefix in _SPEAKER_FROZEN_PREFIXES)
    prefixes = {
        "record": _RECORD_FROZEN_PREFIXES,
        "publish": _PUBLISH_FROZEN_PREFIXES,
        "chat": _CHAT_FROZEN_PREFIXES,
        "speaker": _SPEAKER_FROZEN_PREFIXES,
    }[kind]
    return not is_mutable_pointer(kind, pointer) and any(
        _under(pointer, prefix) for prefix in prefixes
    )


def reject_unknown_wsl_paths(
    document: Mapping[str, Any], *, kind: str, source_workspace_root: str
) -> None:
    marker = source_workspace_root.rstrip("/") + "/"
    for pointer, value in walk_strings(document):
        if marker not in value and value != source_workspace_root.rstrip("/"):
            continue
        if is_mutable_pointer(kind, pointer) or _is_frozen_pointer(kind, pointer):
            continue
        raise PackageRelocationError(
            f"{kind}: unknown external-host path at {pointer_text(pointer)}"
        )


def _pointer_root_roles(kind: str, pointer: JsonPointer) -> frozenset[str]:
    if kind == "record" and speaker_record_pointer(pointer):
        roles = _SPEAKER_ROOT_ROLES.get(pointer[1:])
    else:
        roles = {
        "record": _RECORD_ROOT_ROLES,
        "publish": _PUBLISH_ROOT_ROLES,
        "chat": _CHAT_ROOT_ROLES,
        "speaker": _SPEAKER_ROOT_ROLES,
        }[kind].get(pointer)
    if roles is None:
        raise PackageRelocationError(
            f"{kind}: missing root-role contract at {pointer_text(pointer)}"
        )
    return roles


def match_root_role(
    value: str, *, mappings: Sequence[tuple[str, str]]
) -> tuple[str, str, str] | None:
    """Return (role, source|destination, relative suffix), longest root first."""
    candidates: list[tuple[int, str, str, str]] = []
    for role, (source, destination) in zip(ROOT_ROLES, mappings, strict=True):
        # A role whose two sides coincide needs no projection; reporting it as
        # both sides at once would be a spurious ambiguity.
        sides = (
            (("destination", destination),)
            if source == destination
            else (("source", source), ("destination", destination))
        )
        for side, root in sides:
            if value == root or value.startswith(root + "/"):
                candidates.append((len(root), role, side, value[len(root) :]))
    if not candidates:
        return None
    longest = max(row[0] for row in candidates)
    winners = [row for row in candidates if row[0] == longest]
    if len({row[1:] for row in winners}) != 1:
        raise PackageRelocationError("ambiguous relocation root role")
    _length, role, side, suffix = winners[0]
    return role, side, suffix


def validate_path_root_role(
    value: object,
    *,
    kind: str,
    pointer: JsonPointer,
    mappings: Sequence[tuple[str, str]],
) -> tuple[str, str, str] | None:
    if value is None:
        return None
    if not isinstance(value, str) or not value.startswith("/"):
        raise PackageRelocationError(f"path is not absolute at {pointer_text(pointer)}")
    matched = match_root_role(value, mappings=mappings)
    if matched is None:
        raise PackageRelocationError(
            f"path outside relocation roots (escapes trusted roots) at {pointer_text(pointer)}"
        )
    role, _side, _suffix = matched
    allowed = _pointer_root_roles(kind, pointer)
    if role not in allowed:
        raise PackageRelocationError(
            f"{kind}: wrong root role at {pointer_text(pointer)}: "
            f"expected={','.join(sorted(allowed))} actual={role}"
        )
    return matched


def validate_document_root_roles(
    document: Mapping[str, Any],
    *,
    kind: str,
    mappings: Sequence[tuple[str, str]],
) -> None:
    pointers = {
        "record": RECORD_PATH_POINTERS,
        "publish": PUBLISH_PATH_POINTERS,
        "chat": CHAT_PATH_POINTERS,
        "speaker": SPEAKER_PATH_POINTERS,
    }[kind]
    for pointer in pointers:
        validate_path_root_role(
            get_value(document, pointer),
            kind=kind,
            pointer=pointer,
            mappings=mappings,
        )
    if kind == "record":
        embedded = document.get("speaker_finalization")
        if isinstance(embedded, Mapping):
            for pointer in SPEAKER_PATH_POINTERS:
                validate_path_root_role(
                    get_value(embedded, pointer),
                    kind="record",
                    pointer=("speaker_finalization", *pointer),
                    mappings=mappings,
                )


def project_uniform_host_locators(
    document: Mapping[str, Any],
    *,
    kind: str,
    mappings: Sequence[tuple[str, str]],
    source_workspace_root: str,
    frozen_source_roots: Sequence[str] | None = None,
    frozen_absolute_allowlist: Mapping[JsonPointer, str] | None = None,
) -> dict[str, Any]:
    """Project only contract-listed record/publish runtime locators.

    This is intentionally smaller than :mod:`package_relocation`: uniform-host
    packages have no standalone speaker-finalization manifest, so the full
    three-document relocation transaction cannot be invoked.  It still uses
    exactly the same pointer/root-role/frozen-prefix model.  It does not write,
    hash, or relax evidence; callers must validate their after-image and bind
    derived hashes transactionally.
    """

    if kind not in {"record", "publish", "chat", "speaker"}:
        raise PackageRelocationError("uniform-host projection kind is invalid")
    if len(mappings) != len(ROOT_ROLES):
        raise PackageRelocationError("uniform-host projection root mapping is invalid")
    allowed_frozen = dict(frozen_absolute_allowlist or {})
    for pointer, value in allowed_frozen.items():
        if not _is_frozen_pointer(kind, pointer) or not isinstance(value, str) or not value.startswith("/"):
            raise PackageRelocationError("uniform-host frozen absolute allow-list is invalid")
    frozen_roots = tuple(
        dict.fromkeys(
            (source_workspace_root.rstrip("/"),)
            + tuple(str(root).rstrip("/") for root in (frozen_source_roots or ()))
        )
    )
    if not frozen_roots or any(not root.startswith("/") for root in frozen_roots):
        raise PackageRelocationError("uniform-host frozen source roots are invalid")
    # The primary root retains the legacy unknown-path check.  Additional
    # roots are used only for already-frozen historical evidence; mutable
    # locators below are still restricted to the three relocation roles.
    reject_unknown_wsl_paths(
        document, kind=kind, source_workspace_root=source_workspace_root
    )
    result = copy.deepcopy(dict(document))
    pointers = {
        "record": RECORD_PATH_POINTERS,
        "publish": PUBLISH_PATH_POINTERS,
        "chat": CHAT_PATH_POINTERS,
        "speaker": SPEAKER_PATH_POINTERS,
    }[kind]
    for pointer in pointers:
        value = get_value(result, pointer)
        if value is None:
            continue
        matched = validate_path_root_role(
            value, kind=kind, pointer=pointer, mappings=mappings
        )
        if matched is None:
            continue
        role, side, suffix = matched
        if side == "source":
            set_value(
                result,
                pointer,
                mappings[ROOT_ROLES.index(role)][1] + suffix,
            )
    # A record persists an exact copy of the standalone speaker manifest.
    # Its runtime locators are subject to the same role contract; leaving
    # them private while rewriting the top-level record locators would create
    # an internally inconsistent after-image.
    if kind == "record" and isinstance(result.get("speaker_finalization"), dict):
        for nested in SPEAKER_PATH_POINTERS:
            pointer = ("speaker_finalization", *nested)
            value = get_value(result, pointer)
            if value is None:
                continue
            matched = validate_path_root_role(
                value, kind="record", pointer=pointer, mappings=mappings
            )
            if matched is None:
                continue
            role, side, suffix = matched
            if side == "source":
                set_value(
                    result,
                    pointer,
                    mappings[ROOT_ROLES.index(role)][1] + suffix,
                )
    seen_frozen = set()
    for pointer, value in walk_strings(result):
        if not value.startswith("/"):
            continue
        if is_mutable_pointer(kind, pointer):
            matched = match_root_role(value, mappings=mappings)
            if matched is None:
                raise PackageRelocationError(
                    f"{kind}: mutable path outside relocation roots at {pointer_text(pointer)}"
                )
            validate_path_root_role(value, kind=kind, pointer=pointer, mappings=mappings)
            continue
        if _is_frozen_pointer(kind, pointer):
            if pointer in allowed_frozen:
                if value != allowed_frozen[pointer]:
                    raise PackageRelocationError(
                        f"{kind}: frozen absolute allow-list value drifts at {pointer_text(pointer)}"
                    )
                seen_frozen.add(pointer)
                continue
            if any(value == workspace or value.startswith(workspace + "/") for workspace in frozen_roots):
                continue
            matched = match_root_role(value, mappings=mappings)
            if matched is not None and matched[0] == "repo":
                continue
            raise PackageRelocationError(
                f"{kind}: frozen path escapes source workspace at {pointer_text(pointer)}"
            )
        if not _is_frozen_pointer(kind, pointer):
            raise PackageRelocationError(
                f"{kind}: non-frozen absolute path at {pointer_text(pointer)}"
            )
    if seen_frozen != set(allowed_frozen):
        raise PackageRelocationError("uniform-host frozen absolute allow-list pointer is missing")
    validate_document_root_roles(result, kind=kind, mappings=mappings)
    return result
